<?php

declare(strict_types=1);

namespace Lens\Bundle\IdealBundle\Ideal\Data;

use DateTimeImmutable;
use Lens\Bundle\IdealBundle\Ideal\Data\Type\ConsentStatus;
use Lens\Bundle\IdealBundle\Ideal\IdealResponse;
use Symfony\Component\Validator\Constraints as Assert;

class ConsentDetailedInformation extends IdealResponse
{

    /**
     * ID generated by the Open Banking Service. This should be used to refer to this consent.
     */
    public string $consentId;

    /**
     * Consent status.
     */
    public ConsentStatus $consentStatus;

    /**
     * The ID of the ASPSP. The Open Banking Service needs this information to route the consent and accounts
     * information requests.
     */
    public ?string $aspspId = null;

    /**
     * The data required for PSU authentication and transaction authorisation.
     */
    public ?AuthorisationRequiredData $authorisationRequiredData = null;

    /**
     * Optionally a text for detailed information on the permission handling of the ASPSP is given. E.g. by default a
     * consent is allowing a frequency of up to 4 requests per day. This default is set implicitly by the Open Banking
     * Service. If this parameter is not supported by the ASPSP the initiating party is informed by this.
     */
    public ?string $permissionInformation = null;

    /**
     * This field indicates the maximum frequency for access per day. For a one-off access, this attribute is set to
     * "1".
     */
    public ?string $frequencyPerDay = null;

    /**
     * true, if the consent is for recurring access to the account data.
     * false, if the consent is for one access to the account data.
     */
    public ?bool $recurringIndicator = null;

    /**
     * Date to which the consent is valid.
     */
    public ?string $validUntilDate = null;

    /**
     * The string has to be converted to a Date in ISO Format.
     */
    public ?string $lastActionDate = null;

    /**
     * Specified start date and time for the transaction query period.
     */
    public ?DateTimeImmutable $transactionFromDateTime = null;

    /**
     * Specified end date and time for the transaction query period.
     */
    public ?DateTimeImmutable $transactionToDateTime = null;

    /**
     *
     * A list of hyperlinks to be recognized by the Initiating Party. The actual hyperlinks used in the response depend
     * on the dynamical decisions on authorization approach for example. Remark - All links are full links.
     */
    public ?ConsentStatusLinks $links = null;

    /**
     * Text to be displayed to the PSU.
     */
    #[Assert\Length(max: 1024)]
    public ?string $psuMessage = null;
}
